### ISSUE TITLE
Issues with reading HDF5 files

### ISSUE THREAD

**Issue by Adilet33709** [cta-observatory/dl1-data-handler#103]
I run DL1 Data Handler Demo. I wanted to open HDF5 file by running
reader = DL1DataReader(["Desktop/GA_M1_za10to30_9_13000006_Y_w0.h5"])
it says:
NoSuchNodeError: group ``/`` does not have a child named ``Array_Information``

**Comment by TjarkMiener** [comment]
My apologies for leaving this pending for so long, @Adilet33709! I was forced to disconnect during August.

As already discussed in private, it's recommended to use the common datasets of the MAGIC DL working group hosted at PIC or follow the instructions on the [MAGIC wiki page](https://wiki.magic.pic.es/index.php/MAGIC_Deep_Learning) to create custom datasets. The data format of the DL1 files will change, once the migration to the ctapipe-stage1 data format is completed for MAGIC data. So I would recommend to use the Reader subclasses in the `stage1` branch of DL1DH or directly CTLearn, which takes care of different data formats in the background.

I'm closing this issue, but feel free to reopen it if you still have issues with recommended files.
