### ISSUE TITLE
No support for CTAO data model version >= v5.0.0

### ISSUE THREAD

**Issue by BastienLacave** [cta-observatory/dl1-data-handler#131]
Currently, the field name for retrieving thet image/peak_time transform is incompatible with latest CTAO data model.

should be 
CTAFIELD_3_TRANSFORM_SCALE for image
CTAFIELD_4_TRANSFORM_SCALE for peak time

**Comment by nietootein** [comment]
Thanks for catching this one, @BastienLacave . Yes, I'd move to the latest data model and drop support for older versions and dl1dh data model.

**Comment by maxnoe** [comment]
This is a bit nitpicky, but 

>  latest CTAO data model.

This is not a "CTAO data model" issue. It is the specific data *format* written by ctapipe.

**Comment by TjarkMiener** [comment]
@BastienLacave i think we would need to upgrade to the latest `ctapipe` version and add support for the `v6.0.0` format, while dropping all the `if else` for the other versions and dropping the DL1DH subclass (no need to have a parent class afterwards). The shape for R1 waveforms have also changed to (n_channels, n_pixels, n_samples), which should break the current reading.

**Comment by TjarkMiener** [comment]
solved by #133
