### ISSUE TITLE
calibration and pixel saturation

### ISSUE THREAD

**Issue by vuillaut** [cta-observatory/dl1-data-handler#40]
Hi

As discussed with @nietootein last week, we realized that the calibration is not currently properly done in the code.

Q1: Are both channels saved in the HDF5 files (I think not but I don't have a datafile here to double check)?

If so, we could in principle select the right channel afterward (when loading data) but I would highly recommend option B:

The channel selection should be done during the calibration and thus we write only calibrated image (with combined channels) to disk.

However:
- to my knowledge, there is nothing to do that in ctapipe.
- the range of pixel values is camera dependent.

This means we need to code the pixel selection, and get the saturation values for all cameras used in the simulations (this could be different for different productions).

Even though the saturated pixels represent a vast minority, this could really affect the performances. Especially, it could explain the quite poor performances we observe at higher energies (TBC of course).

**Comment by bryankim96** [comment]
Karl mentions that they're preparing to implement automatic gain selection soon in ctapipe in this release:

https://github.com/cta-observatory/ctapipe/releases/tag/v0.6.0

I also found the implementation in master (apparently still unused as of now) and some discussion:

https://github.com/cta-observatory/ctapipe/blob/master/ctapipe/calib/camera/gainselection.py
https://github.com/cta-observatory/ctapipe/issues/419

As far as I know it is not implemented yet in the most recent release (v0.6.2), which is the current supported version for DL1DH. 

Until that feature is added, it should be very easy to quick fix/patch ourselves (essentially following the implementation they've already planned in https://github.com/cta-observatory/ctapipe/blob/master/ctapipe/calib/camera/gainselection.py) . How would you guys like to handle it? I notice that in the ctapipe implementation they consider two options, pixel-by-pixel selection between gain channels, and sample-by-sample selection. Do you think we need to worry about the latter, or would the former be sufficient?

Let me know what you guys would prefer and I will go ahead and add the fix.

**Comment by vuillaut** [comment]
I am writing the patch for `data_handler` right now.
I just don't see where is the channel selection done in the code.

**Comment by vuillaut** [comment]
> I just don't see where is the channel selection done in the code.

Nevermind, found it just after I commented.
I'll submit a patch.

**Comment by vuillaut** [comment]
Ok I am actually done but things got really messy because my clone was still the `image-extractor` one and I gotta go now.
I'll make a PR tonight for you @bryankim96.

**Comment by bryankim96** [comment]
Sorry about that, I think it may have been because I just rewrote the commit history to fix the other repository size issue you mentioned. 

Ok, that sounds good! Thanks.

**Comment by vuillaut** [comment]
> Sorry about that, I think it may have been because I just rewrote the commit history to fix the other repository size issue you mentioned.

No problem, I just made a fresh clone as you said. I was just in a hurry and could not get this done yesterday.

**Comment by bryankim96** [comment]
Closed (at least for now, until it is implemented in ctapipe and we can switch over) by #42.
