### ISSUE TITLE
Add processing functions from CTLearn and GammaLearn

### ISSUE THREAD

**Issue by aribrill** [cta-observatory/dl1-data-handler#43]
Update processor.py with Transforms that implement desired processing functions from CTLearn and GammaLearn. The most efficient approach might be to implement first the highest-priority functions that we plan to use, and any others only later as needed. This is Task 1 in #35.

The functions currently implemented in CTLearn are:
- Cropping
  - This consists of three parts: cleaning the image, calculating and appending the image centroid coordinates, and cropping each input about the centroid, so these could be implemented as separate transforms. The cleaning is needed as an intermediate step to calculate accurate centroids.
  - Arguments
    - image cleaning method (two-level or None)
    - bounding box size for each telescope type
    - two-level cleaning thresholds for each telescope type 
    - whether to return the cleaned or uncleaned images
  - Problem: with cleaning and cropping as separate Transforms, it's not clear to me how to implement the option to use cleaning for calculating the centroids while still returning the uncleaned, but cropped, images.
- Normalization
  - Only option is log normalization, which consists of subtracting from each pixel the minimum value from all selected images (probably best to have the users calculate themselves), then taking the natural log
- Sorting
  - trigger: order images by all triggered followed by all blank images
  - size: order images by largest to smallest total sum of pixel values

To me, the highest priority functions of these are sorting (required for our CNN-RNN implementation) and perhaps image cleaning. As I recall, we ended up not using cropping or log normalization in our benchmarks, as we found them to have little effect on classification performance.

@mikael10j, what are the processing functions implemented in GammaLearn?

I think the next steps are to decide which processing functions we want to have in DL1DH and then split up the work of implementing them. Are there any other functions we need but are in neither package?

**Comment by mikael10j** [comment]
Hi Ari,
in GammaLearn we have:
* EnergyToLog
* ImpactToKm
* TelescopePositionToKm
* NumpyToTensor
  * transforms numpy data into torch tensor.
* RotateImage
  * for data augmentation, associated with "augment_via_rotation" function. In that case the transforms is not applied to the dataset itself, but to a copy of it.

as Transforms (i.e. applied to data when loading a batch).
We have also:
* normalize_pixels
  * with different options, but don't really use it.
* center_time
  * to center the time maps based on the highest intensity pixel. The image is first cleaned.
* cleaning_filter
  * with an option to apply it or not. If not it only discards the images that would not pass the cleaning.

as "filtering" operations, as they are applied only once before the training.
As priority functions I would add to cleaning and image sorting, transforming energy to log and the xCore and yCore to km. It would be nice also to have a filtering function based on the cleaning result (is it another topic ?).
About the cropping transform, it could simply call the cleaning one, what do you think ?

**Comment by TjarkMiener** [comment]
Solved even before v0.10.0.
