### ISSUE TITLE
Add bins argument to reader.num_examples() method

### ISSUE THREAD

**Issue by aribrill** [cta-observatory/dl1-data-handler#48]
The method reader.num_examples() calculates the number of examples in the dataset, grouped by an arbitrary set of features (typically the class label). It would not work if continuous features (e.g. mc_energy) are used as labels, since those features are more or less unique for a given event. Instead, it would be useful to group these features by bins.

To enable this, add an argument to this method which is a dictionary of feature names to bins and use it when grouping. If bins are specified for a feature, they would override the default grouping behavior when grouping the examples.

**Comment by TjarkMiener** [comment]
Hi @aribrill. I think this should be done in the CTA DL1 benchmarking notebooks, which are already supporting this. However, `reader.num_examples()` is still very useful for balancing the dataset in the particle classification task for us deep learners. Feel free to reopen, if you have a strong opinion about this feature :-)
