### ISSUE TITLE
Add image mapping method to return unmapped vectors

### ISSUE THREAD

**Issue by aribrill** [cta-observatory/dl1-data-handler#49]
As mentioned by @mikael10j in #46, the image mapper should have a method to return the unmapped vectors. Because this behavior most closely reflects the HDF5 data, it should be the default method if no method is specified.

**Comment by TjarkMiener** [comment]
Do we want to use the unmapped vectors? Why we don't use 'oversampling' as the default method?

**Comment by aribrill** [comment]
I don't think we have any plans to use that in CTLearn, but a basic use case might be as input for a traditional NN or other ML algorithm expecting an input vector. An argument for returning vectors as default is that it represents the least amount of processing possible. An argument against would be that the images were originally 2D and the user expectation would be to return them that way, since the 1D vectors are an artifact of the HDF5 file format. @mikael10j any input on this?

**Comment by mikael10j** [comment]
I totally agree with "the least amount of processing possible" argument.

**Comment by aribrill** [comment]
I mean that the images come from a set of camera pixels with a particular 2D physical arrangement.

**Comment by vuillaut** [comment]
> An argument against would be that the images were originally 2D and the user expectation would be to return them that way, since the 1D vectors are an artifact of the HDF5 file format. @mikael10j any input on this?

Hi @aribrill 
What do you mean the images were originally 2D?
In ctapipe they are certainly not.
Either we talk about waveforms, and they are 3D of shape `(n_gain, n_pixels, n_samples)` or we talk about calibrated images and their shape is `(n_gain, n_pixels)` and will most probably be `(n_pixels,)` since real data will contain only one channel (so 1D).

The format on disk does not really matter here, it's how the reader reads the data that makes the object (and thus the dimension).

**Comment by vuillaut** [comment]
> I mean that the images come from a set of camera pixels with a particular 2D physical arrangement.

Ok but since they don't follow a grid arrangement, I don't really expect to get an image as a 2D array 🤔

**Comment by aribrill** [comment]
> Either we talk about waveforms, and they are 3D of shape (n_gain, n_pixels, n_samples) or we talk about calibrated images and their shape is (n_gain, n_pixels) and will most probably be (n_pixels,) since real data will contain only one channel (so 1D).

Right. I spoke imprecisely and neglected the channel dimension. I was referring to two spatial coordinates.

> Ok but since pixels don't follow a grid arrangement, I don't really expect to get an image as a 2D array

You would if you worked on the SCT :smile: (but yes, that makes sense).

**Comment by TjarkMiener** [comment]
I just thought it isn't really useful for us, since we will call map_image(unmapped_vector, camera_type) and the returning value will be unmapped_vector. It's also a bit confusing, when map_image() is returning a 2D or 1D array.

**Comment by mikael10j** [comment]
@TjarkMiener, when the mapping method is 'axial_addressing' could the image mapper return the unmapped vector ?

**Comment by TjarkMiener** [comment]
With image mapper you mean the function map_image() in the image mapper, right? Because we will retrieve the index matrix with get_indexmatrix() and not use map_image() for axial addressing. Should be relative easy and fast to implement. I can also add a new mapping method 'unmapped' to return the unmapped vector. What would be better?

**Comment by mikael10j** [comment]
I guess not calling map_image() makes sense, to save (a bit) resources.

**Comment by TjarkMiener** [comment]
I was discussing this issue with @nietootein. You need that unmapped vector as an input for IndexedConv (with the index matrix), right? So not calling map_image() in the reader (line 323), when 'axial addressing' is selected is totally reasonable to me.

**Comment by TjarkMiener** [comment]
In order to retrieve the index matrix, we have to do most of the calculations in the init of image mapper. So it doesn't make sense to bypass the calculating of the mapping table/s.

**Comment by mikael10j** [comment]
> In order to retrieve the index matrix, we have to do most of the calculations in the init of image mapper. So it doesn't make sense to bypass the calculating of the mapping table/s.
Absolutely.
If the function `_get_image` returns the vector in case of axial_addressing it's perfect.

**Comment by TjarkMiener** [comment]
Is anything else missing for the IndexedConv?

**Comment by mikael10j** [comment]
Nope.
