### ISSUE TITLE
Single-thread writting

### ISSUE THREAD

**Issue by nietootein** [cta-observatory/dl1-data-handler#51]
It seems that single-thread writing is preferred for the processing on the grid (see [here](https://forge.in2p3.fr/issues/35992#note-37)). @bryankim96, is [write_data_single_thread.py](https://github.com/cta-observatory/dl1-data-handler/blob/master/scripts/write_data_single_thread.py) ready for production? Would it make sense to have a single script and add the option to select single or multi-thread processing to the config file?

**Comment by bryankim96** [comment]
I can verify that that the script is in a fine state, I used it quite a bit with no issues. Please feel free to use it if it's more convenient. 

I will make the change you suggested later today so it will be available for you tomorrow morning (your time) if you want it. However, if there's any urgency, write_data_single_thread.py should work just as well.

**Comment by bryankim96** [comment]
Closed by #54.
