### ISSUE TITLE
Issues reducing SCT data

### ISSUE THREAD

**Issue by nietootein** [cta-observatory/dl1-data-handler#52]
I tried to reduce some SCT from prod3b data with [write_data.py](https://github.com/cta-observatory/dl1-data-handler/blob/v0.7.4/scripts/write_data.py) (v0.7.4) and I'm getting the following error:

> `Process Process-1:
> Traceback (most recent call last):
>   File "/home/nieto/Software/anaconda3/envs/dl1dh-v074/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
>     self.run()
>   File "/home/nieto/Software/anaconda3/envs/dl1dh-v074/lib/python3.7/multiprocessing/process.py", line 99, in run
>     self._target(*self._args, **self._kwargs)
>   File "/home/nieto/Software/anaconda3/envs/dl1dh-v074/lib/python3.7/site-packages/dl1_data_handler/writer.py", line 858, in _process_data
>     event_source = io.event_source(filename)
>   File "/home/nieto/Software/anaconda3/envs/dl1dh-v074/lib/python3.7/site-packages/ctapipe/io/eventsourcefactory.py", line 102, in event_source
>     **kwargs)
>   File "/home/nieto/Software/anaconda3/envs/dl1dh-v074/lib/python3.7/site-packages/ctapipe/core/factory.py", line 254, in produce
>     instance = factory._instance
>   File "/home/nieto/Software/anaconda3/envs/dl1dh-v074/lib/python3.7/site-packages/ctapipe/core/factory.py", line 226, in _instance
>     instance = product(config, parent, **kwargs)
>   File "/home/nieto/Software/anaconda3/envs/dl1dh-v074/lib/python3.7/site-packages/ctapipe/io/simteleventsource.py", line 22, in __init__
>     self.file_ = SimTelFile(self.input_url)
>   File "/home/nieto/Software/anaconda3/envs/dl1dh-v074/lib/python3.7/site-packages/eventio/simtel/simtelfile.py", line 136, in __init__
>     self.telescope_descriptions[o.telescope_id][key] = o.parse()
>   File "/home/nieto/Software/anaconda3/envs/dl1dh-v074/lib/python3.7/site-packages/eventio/simtel/objects.py", line 243, in parse
>     assert_exact_version(self, supported_version=1)
>   File "/home/nieto/Software/anaconda3/envs/dl1dh-v074/lib/python3.7/site-packages/eventio/version_handling.py", line 11, in assert_exact_version
>     given_version=self.header.version,
> NotImplementedError: Unsupported version of CameraOrganization: only supports version 1got 2`

This error seems to be related to [#135](https://github.com/cta-observatory/pyeventio/issues/135) in pyhessio and fixed in v0.16.1. The latest ctapipe release, used by dl1-data-handler, includes pyeventio v0.11.0. It seems we either need to wait for a new ctapipe release that includes an updated pyeventio version or add pyeventio >v0.16.1as a dl1-data-handler dependency.

**Comment by bryankim96** [comment]
It looks like v0.20 of eventio is already available as a conda package, so it should be no problem adding it as a dependency (no need to fiddle with getting tarballs from source). The only possible thing that concerns me is whether there might be any incompatibility between eventio v0.20 and ctapipe v0.6.2. From reading the release notes it doesn't look like there were any groundbreaking changes between v0.11 and v0.20, but who knows... I can give it a shot and run some tests. If it looks good I think it would probably be worth it overall to add the fix, even if it's only temporary until the next ctapipe release.

**Comment by MaxNoe** [comment]
There were breaking changes in 0.17.1 (renaming of fields) and 0.20.1 (use a faster method to read gzip files, which broke the `EventSeeker`.

https://github.com/cta-observatory/ctapipe/pull/966
https://github.com/cta-observatory/ctapipe/pull/1062

**Comment by MaxNoe** [comment]
So: updating should be possible using ctapipe 0.6.2, but for newer versions of eventio you need newer versions of ctapipe.

**Comment by TjarkMiener** [comment]
Seems to be solved by updating the ctapipe version (which is even the case for the deprecated DL1DHWriter). Anyhow, solved by using the ctapipe process tool.
