### ISSUE TITLE
ImageMapper error: weird shape for LSTCam [shift_imagemapper]

### ISSUE THREAD

**Issue by mikael10j** [cta-observatory/dl1-data-handler#57]
Trying to create a reader for LSTCam I get a ValueError:
`dataset = DL1DataReader(files, selected_telescope_type='LST_LSTCam', selected_telescope_ids=[1],
                        event_info=['mc_energy', 'core_x', 'core_y', 'alt', 'az', 'mc_particle'], 
                        )`

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-10-1fa8a2f0bdd4> in <module>()
      1 dataset = DL1DataReader(files, selected_telescope_type='LST_LSTCam', selected_telescope_ids=[1],
----> 2                         event_info=['mc_energy', 'core_x', 'core_y', 'alt', 'az'],
      3 #                         mapping_settings={'mapping_method': {'LST_LSTCam': 'axial_addressing'}}
      4                         )

~/dl1-data-handler/dl1_data_handler/reader.py in __init__(self, file_list, mode, selected_telescope_type, selected_telescope_ids, selection_string, intensity_selection, shuffle, seed, image_channels, mapping_method, mapping_settings, array_info, event_info, transforms, validate_processor)
    173         self.image_channels = image_channels
    174         self.image_mapper = ImageMapper(channels=self.image_channels,
--> 175                                         **mapping_settings)
    176 
    177         if array_info is None:

~/dl1-data-handler/dl1_data_handler/image_mapper.py in __init__(self, camera_types, mapping_method, padding, interpolation_image_shape, rotate_camera, mask_interpolation, channels)
    127             self.index_matrixes[camtype] = None
    128             # Calculating the mapping tables for the selected camera types
--> 129             self.mapping_tables[camtype] = self.generate_table(camtype)
    130 
    131     def map_image(self, pixels, camera_type):

~/dl1-data-handler/dl1_data_handler/image_mapper.py in generate_table(self, camera_type)
    189             # Finding the nearest point in the hexagonal grid for each point in the square grid
    190             tree = spatial.cKDTree(hex_grid)
--> 191             nn_index = np.reshape(tree.query(table_grid)[1], (output_dim, output_dim))
    192             # Store the nn_index array in the index_matrix. Replace virtual pixel indexes with -1.
    193             if map_method == 'axial_addressing':

~/anaconda3/lib/python3.6/site-packages/numpy/core/fromnumeric.py in reshape(a, newshape, order)
    255            [5, 6]])
    256     """
--> 257     return _wrapfunc(a, 'reshape', newshape, order=order)
    258 
    259 

~/anaconda3/lib/python3.6/site-packages/numpy/core/fromnumeric.py in _wrapfunc(obj, method, *args, **kwds)
     50 def _wrapfunc(obj, method, *args, **kwds):
     51     try:
---> 52         return getattr(obj, method)(*args, **kwds)
     53 
     54     # An AttributeError occurs if the object does not have

ValueError: cannot reshape array of size 9800 into shape (98,98)

**Comment by TjarkMiener** [comment]
I have a guess. Try to reinstall dl1dh. I guess @bryankim96 and me saw the same dimension mismatch. It's the FACT camera, who is causing this. The commit eb7b0de (updating the ctapipe extra version) should fix this bug. 

Side note: Right now you are calling the default ImageMapper, which will calculate the mapping tables for all telescopes (with oversampling). From the error message I see you commented out the mapping_settings. The ImageMapper is using the camera names from [ctapipe](https://github.com/cta-observatory/ctapipe/blob/master/ctapipe/instrument/camera.py), which differs from the one used in the Reader. The mapping_settings should look like this for your purpose:
`mapping_settings = {'camera_types': ['LSTCam'],'mapping_method': {'LSTCam': 'axial_addressing'}}`
Is this right, @aribrill?

The argument `camera_types` is telling the ImageMapper, which mapping table/s it should calculate. Other cameras will be ignored.

**Comment by aribrill** [comment]
I believe those would be the right `mapping_settings`.

As an additional comment on the camera types, for a telescope type, the camera type is the part after the underscore, so for `LST_LSTCam` the camera type is `LSTCam`. This is slightly different from ctapipe, which uses a colon `:` as the separator instead of an underscore, and includes hyphens `-` in the camera types, neither of which are compatible with PyTables. The names are converted from ctapipe by replacing the colon with an underscore and stripping out any hyphens.

To clarify the behavior of the `camera_types` argument, if not provided, the default behavior is to calculate tables for all telescopes, so it is optional but omitting it would make initialization a bit slower.

**Comment by TjarkMiener** [comment]
Does reinstalling dl1dh solved the error?

**Comment by mikael10j** [comment]
Yes it does, thank you.
