### ISSUE TITLE
reader: Data selection

### ISSUE THREAD

**Issue by mikael10j** [cta-observatory/dl1-data-handler#58]
Realizing the data selection via `f.root.Events.where` and a `cut_condition` string is very nice and simple. However, if the selection doesn't apply on the event info (like the event intensity or the result of the cleaning), or if the selection needs more complex operations than the ones listed [here](https://www.pytables.org/usersguide/condition_syntax.html#condition-syntax), we can't use it. And that's exactly why `_select_event_intensity` is implemented. What do you think of a more generic `_select_event` function which take in argument a dictionary of `{filtering.function: filtering.parameters}` ? So we could easily add filtering functions without modifying the core code of the reader. If you agree I can take care of coding it.

**Comment by aribrill** [comment]
That sounds like an excellent idea. Please do it!
