### ISSUE TITLE
Investigating gain selection issue

### ISSUE THREAD

**Issue by vuillaut** [cta-observatory/dl1-data-handler#73]
I open the thread to follow the gain selection issue raised by PR #72.

It seems I could reproduce an (the?) issue in the case of waveforms of shape `(n_gain, n_pix, 1)` - that would correspond to `ASTRICam`.
In this case the `gain_mask` from `_, gain_mask = gain_selector.select_gains(cam_id, waveform)` is of shape `(n_pix,)`.

Maybe @riwim or @mackaiver can tell me if that's the issue they encountered.

**Comment by TjarkMiener** [comment]
Solved by the ctapipe process tool.
