### ISSUE TITLE
No module named dl1_data_handler.writer

### ISSUE THREAD

**Issue by NanuSai** [cta-observatory/dl1-data-handler#80]
Hey, I'm unsure of how to installation process is, but I have done the following:
1. Created conda environment with python 3.7 ( python 3.6 gave me compability conflict because of cuda 10.2).
2. Installed as per the instructions, checked out v0.7.3.
3. Typed the following command 
![import error](https://user-images.githubusercontent.com/45007169/73756443-8ecd4700-478d-11ea-8d40-9a79f2dafef1.png)

**Comment by MaxNoe** [comment]
Why are you using sudo? When using sudo, you'll drop in a shell, where conda is not setup and probably use the system python that has no libraries installed.

To confirm, what does `sudo which python` return?

**Comment by NanuSai** [comment]
You're right!! 
It shows /usr/bin/python thank you so much. I'm closing this issue
