### ISSUE TITLE
Number of loaded events differs for DL1Reader in 'mono' and 'stereo' mode

### ISSUE THREAD

**Issue by TjarkMiener** [cta-observatory/dl1-data-handler#82]
With the LST dataset (produced by @vuillaut ), I'm getting following numbers, when running CTLearn in load_only mode with DL1Reader in 'mono' and 'stereo' mode. Is this expected, because it's a LST mono reduction?

Mono mode:
```
INFO:Logging has been correctly set up
INFO:Loading data:
INFO:For a large dataset, this may take a while...
INFO:Batch size: 64
INFO:Number of training steps per epoch: 32046
INFO:Number of training steps between validations: 2500
INFO:Examples for total dataset:
INFO:  Total number: 2278845
INFO:  Breakdown by particletype:
INFO:    proton: 1136452
INFO:    gamma: 1142393
INFO:
INFO:Examples for training:
INFO:  Total number: 2050960
INFO:  Breakdown by particletype:
INFO:    proton: 1023014
INFO:    gamma: 1027946
INFO:
INFO:Examples for validation:
INFO:  Total number: 227885
INFO:  Breakdown by particletype:
INFO:    gamma: 114447
INFO:    proton: 113438
INFO:
```

Stereo mode:
```
INFO:Logging has been correctly set up
INFO:Loading data:
INFO:For a large dataset, this may take a while...
INFO:Batch size: 64
INFO:Number of training steps per epoch: 17411
INFO:Number of training steps between validations: 2500
INFO:Examples for total dataset:
INFO:  Total number: 1238154
INFO:  Breakdown by particletype:
INFO:    gamma: 574983
INFO:    proton: 663171
INFO:
INFO:Examples for training:
INFO:  Total number: 1114338
INFO:  Breakdown by particletype:
INFO:    gamma: 517461
INFO:    proton: 596877
INFO:
INFO:Examples for validation:
INFO:  Total number: 123816
INFO:  Breakdown by particletype:
INFO:    proton: 66294
INFO:    gamma: 57522
INFO:
```

**Comment by aribrill** [comment]
It's not clear to me there is a contradiction. In stereo mode, the examples are multi-image events, while in mono mode they are images, so it makes sense there's more examples in mono mode.

**Comment by vuillaut** [comment]
Hi.
I am not sure I understand the question/issue here.
Could you elaborate, please?

**Comment by TjarkMiener** [comment]
Thanks for clarification, @aribrill! 
Hi @vuillaut, 
Sorry, I wasn't very precise with explaining the issue. When I tried to analyse 'your' LST dataset with our stereo models (cnn_rnn model), it turned out that they are performing worst than the mono telescope model (single_tel model), while we normally expect the stereo models to perform better. We are currently underperforming previous benchmark (different dataset, **but** also different versions of DL1-DataHandler and CTLearn) with the cnn_rnn model by 10% in particle classification accuracy. 
Since the cnn_rnn implementation haven't changed much, I'm suspecting the issue is caused by the data handler (> v0.8.0) and not CTLearn.

**Comment by vuillaut** [comment]
Ha ok.
You did not mention performances issue before.

So, now you get `stereo LST < mono LST` and `stereo LST < stereo CTA dataset`?

For the first point, my first question would be are you in the same conditions?
In particular the number of training events. As @aribrill said, you'll have much more data to train on in mono, that could explain the difference?

For the second point, I am a bit more puzzled (except asking the same question as for point 1).

**Comment by TjarkMiener** [comment]
Yes, that's what I'm getting. Since we are almost getting `mono LST = mono CTA dataset`, I would expect to get `stereo LST = stereo CTA dataset`. Our previous benchmarks show that `mono CTA dataset < stereo CTA dataset` for all the telescope types, so I suspect a software bug.
